//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videfix.Tray.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceManager;
        
        private static global::System.Globalization.CultureInfo resourceCulture = System.Globalization.CultureInfo.CurrentUICulture;

		private static global::System.Resources.ResourceManager invariantResourceManager;

	    private static global::System.Globalization.CultureInfo invariantResourceCulture = System.Globalization.CultureInfo.GetCultureInfo("en-GB");

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceManager, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
	                    $"Videfix.Tray.Resources.Strings_{resourceCulture.TwoLetterISOLanguageName}",
	                    typeof(Strings).Assembly);
                    resourceManager = temp;
                }
                return resourceManager;
            }
        }

		/// <summary>
	    ///   Gibt die zwischengespeicherte invariante ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
	    /// </summary>
	    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	    internal static global::System.Resources.ResourceManager InvariantResourceManager
	    {
		    get
		    {
			    if (object.ReferenceEquals(invariantResourceManager, null))
			    {
				    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
					    $"Videfix.Tray.Resources.Strings_{invariantResourceCulture.TwoLetterISOLanguageName}",
					    typeof(Strings).Assembly);
				    invariantResourceManager = temp;
			    }
			    return invariantResourceManager;
		    }
	    }

        /// <summary>
		///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
		///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Copyright © Christoph Thiede 2020. ähnelt.
		/// </summary>
		internal static string AboutDialog_Copyright => GetString(nameof(AboutDialog_Copyright));

		private static string GetString(string key)
		{
			return ResourceManager.GetString(key, resourceCulture)
				   ?? InvariantResourceManager.GetString(key, invariantResourceCulture);
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Videfix automatically saves your window&apos;s arrangement and restores them after a restart of your PC. ähnelt.
		/// </summary>
		internal static string AboutDialog_Description => GetString(nameof(AboutDialog_Description));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Latest backup created: {0} ähnelt.
		/// </summary>
		internal static string AboutDialog_LatestBackupCreated => GetString(nameof(AboutDialog_LatestBackupCreated));
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Not any backup created yet) ähnelt.
        /// </summary>
        internal static string AboutDialog_NoBackupCreated => GetString(nameof(AboutDialog_NoBackupCreated));

		internal static string AboutDialog_StartWithWindows => GetString(nameof(AboutDialog_StartWithWindows));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Window arrangements ähnelt.
		/// </summary>
		internal static string BrowseArrangementsDialog_ArrangementFilter => GetString(nameof(BrowseArrangementsDialog_ArrangementFilter));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Browse arrangements ... ähnelt.
		/// </summary>
		internal static string BrowseArrangementsDialog_Title => GetString(nameof(BrowseArrangementsDialog_Title));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Close the other dialog window and try again. ähnelt.
		/// </summary>
		internal static string BusyErrorDialog_Details => ResourceManager.GetString(nameof(BusyErrorDialog_Details));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Command cannot be executed because another dialog window is opened ähnelt.
		/// </summary>
		internal static string BusyErrorDialog_Instruction => GetString(nameof(BusyErrorDialog_Instruction));

		internal static string ConfigureStartWithWindowsErrorDialog_Instruction => GetString(nameof(ConfigureStartWithWindowsErrorDialog_Instruction));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die About Videfix ähnelt.
		/// </summary>
		internal static string ContextMenu_About_String => GetString(nameof(ContextMenu_About_String));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
		/// </summary>
		internal static string ContextMenu_Exit_String => GetString(nameof(ContextMenu_Exit_String));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Restore arrangement ähnelt.
		/// </summary>
		internal static string ContextMenu_Restore_String => GetString(nameof(ContextMenu_Restore_String));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Save arrangement ähnelt.
		/// </summary>
		internal static string ContextMenu_Save_String => GetString(nameof(ContextMenu_Save_String));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Videfix ähnelt.
		/// </summary>
		internal static string Dialog_AppTitle => GetString(nameof(Dialog_AppTitle));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Hide error details ähnelt.
		/// </summary>
		internal static string ErrorDialog_HideDetails => GetString(nameof(ErrorDialog_HideDetails));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Show error details ähnelt.
		/// </summary>
		internal static string ErrorDialog_ShowDetails => GetString(nameof(ErrorDialog_ShowDetails));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Please try restarting the application. If you can reproduce the problem, you might contact the developer. ähnelt.
		/// </summary>
		internal static string GeneralErrorDialog_Details => GetString(nameof(GeneralErrorDialog_Details));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Videfix has encountered a problem and needs to close ähnelt.
		/// </summary>
		internal static string GeneralErrorDialog_Instruction => GetString(nameof(GeneralErrorDialog_Instruction));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Videfix has been started without administrative privileges.
		///
		///If you do not elevate it, windows running elevated cannot be captured or arranged. ähnelt.
		/// </summary>
		internal static string NotElevatedWarningDialog_Details => GetString(nameof(NotElevatedWarningDialog_Details));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Windows running elevated will not be captured. ähnelt.
		/// </summary>
		internal static string NotElevatedWarningDialog_Ignore_Details => GetString(nameof(NotElevatedWarningDialog_Ignore_Details));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Continue unelevated ähnelt.
		/// </summary>
		internal static string NotElevatedWarningDialog_Ignore_Title => GetString(nameof(NotElevatedWarningDialog_Ignore_Title));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Run Videfix as administrator ähnelt.
		/// </summary>
		internal static string NotElevatedWarningDialog_Instruction => GetString(nameof(NotElevatedWarningDialog_Instruction));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Restart as administrator ähnelt.
		/// </summary>
		internal static string NotElevatedWarningDialog_RestartElevated => GetString(nameof(NotElevatedWarningDialog_RestartElevated));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Terminate Videfix ähnelt.
		/// </summary>
		internal static string NotElevatedWarningDialog_Terminate => GetString(nameof(NotElevatedWarningDialog_Terminate));

		internal static string OfferRestoreDialog_Accept => GetString(nameof(OfferRestoreDialog_Accept));
		internal static string OfferRestoreDialog_Accept_Details => GetString(nameof(OfferRestoreDialog_Accept_Details));
		internal static string OfferRestoreDialog_Decline => GetString(nameof(OfferRestoreDialog_Decline));
	    internal static string OfferRestoreDialog_Details => GetString(nameof(OfferRestoreDialog_Details));
	    internal static string OfferRestoreDialog_Instruction => GetString(nameof(OfferRestoreDialog_Instruction));

		internal static string Registry_ApplicationName => GetString(nameof(Registry_ApplicationName));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Browse arrangements ... ähnelt.
		/// </summary>
		internal static string RestoreArrangementDialog_Browse => GetString(nameof(RestoreArrangementDialog_Browse));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Which arrangement would you like to restore? ähnelt.
		/// </summary>
		internal static string RestoreArrangementDialog_Instruction => GetString(nameof(RestoreArrangementDialog_Instruction));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Restore last saved arrangement ähnelt.
		/// </summary>
		internal static string RestoreArrangementDialog_RestoreLastSaved => GetString(nameof(RestoreArrangementDialog_RestoreLastSaved));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Arrangement saved at {0} ähnelt.
		/// </summary>
		internal static string RestoreArrangementDialog_RestoreLastSaved_Details => GetString(nameof(RestoreArrangementDialog_RestoreLastSaved_Details));
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The window arrangement has been restored. ähnelt.
        /// </summary>
        internal static string RestoredDialog_Message => GetString(nameof(RestoredDialog_Message));

		internal static string RestoreErrorDialog_Details => GetString(nameof(RestoreErrorDialog_Details));
	    internal static string RestoreErrorDialog_Instruction => GetString(nameof(RestoreErrorDialog_Instruction));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die The window arrangement has been saved. ähnelt.
		/// </summary>
		internal static string SavedDialog_Message => GetString(nameof(SavedDialog_Message));

		internal static string SaveErrorDialog_Instruction => GetString(nameof(SaveErrorDialog_Instruction));

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Videfix ähnelt.
		/// </summary>
		internal static string SystemTray_AppTitle => GetString(nameof(SystemTray_AppTitle));

		internal static string BackupErrorDialog_Instruction => GetString(nameof(BackupErrorDialog_Instruction));
	}
}